
<div>
    <div >
        <form method="post">
            <input type="text" id="mail" class="fadeIn second" name="mail" placeholder="mail">
            <input type="password" id="password" class="fadeIn third" name="password" placeholder="password">
            <input type="password" id="password2" class="fadeIn third" name="password2" placeholder="repeat password">
            <input type="submit" class="fadeIn fourth" value="Sign up">
        </form>

    </div>
</div>