<?php
/**
 * @var $property_obj
 */
?>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MALLORCASA</title>
</head>
<body>
<div class="container">
    <h2 class="text-center"><span><a href="list.php">Mallorcasa</a></span></h2>
    <?php if (isset($_SESSION["userMail"])) { ?>
        <div style="position: absolute; top: 10px; right:10px">
            <a href="../Controllers/logoutController.php" class="btn btn-info btn-round" role="button">
                Logout
            </a>
        </div>
    <?php } else { ?>
        <div style="position: absolute; top: 10px; right: 10px">
            <a href="../Controllers/loginController.php" class="btn btn-info btn-round" role="button">
                Login
            </a>
            <a href="../Controllers/signupController.php" class="btn btn-info btn-round" role="button">
                Darse de alta
            </a>
        </div>
    <?php } ?>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide-to="0" class='active' aria-current='true' aria-label="Slide 1"></button>
                    <?php for ($i = 1; $i < count($property_obj->property->images); $i++) { ?>
                        <button type="button" data-bs-target="#carouselExampleIndicators"
                                data-bs-slide-to="<?php echo $i ?>" aria-label="Slide <?php echo $i + 1 ?>"></button>
                    <?php } ?>

                </div>
                <div class="carousel-inner">
                    <?php foreach ($property_obj->property->images as $image) { ?>
                        <div class="carousel-item <?php echo($property_obj->property->images[0]->id == $image->id ? "active" : "") ?>">
                            <img src="<?php echo $image->url ?>"
                                 class="d-block w-100"
                                 alt="13850">
                        </div>
                    <?php } ?>
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Descripcion</h5>
                    <?php echo $property_obj->property->description ?>
                </div>
            </div>
            <br>

        </div>
        <div class="col-md-4">
            <div class="card sticky-top" style="top: 20px;">
                <div class="card-body">
                    <h5 class="card-title">Deetalles</h5>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-info"></i>
                            Id
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->id ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-globe"></i>
                            Pais
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->country->name ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-flag"></i>
                            Provincia
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->state->name ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-building-o"></i>
                            Ciudad
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->city->name ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-building"></i>
                            Vecindario
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->neighborhood->name ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-envelope"></i>
                            Código Postal
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->zipcode ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-calendar"></i>
                            Publicado
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->date->date ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-bath"></i>
                            Baños
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->bathrooms ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-arrow-circle-up"></i>
                            Plantas
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->floor ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-bed"></i>
                            Habitaciones
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->rooms ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-arrows-alt"></i>
                            Superficie
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->surface ?></span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <span>
                                <i class="fa fa-eur"></i>
                            Precio
                            </span>
                            <span class="badge bg-primary rounded-pill"><?php echo $property_obj->property->price ?>€</span>
                        </li>
                    </ul>

                </div>
            </div>
            <br>
        </div>
    </div>
</div>
</body>

</html>
